### ISSUE TITLE
User can log in/log out of your app as a user

### ISSUE THREAD

**Issue by patrick141** [patrick141/QuickCash#3]
User can log in/log out of your app as a user

**Comment by qillura** [comment]
1.  create usertable in parse
2. create api
3. use api on client
4. create fragment and UI on client

**Comment by patrick141** [comment]
-Create Login and Signup Screen. 
-User can sign into their account.
      -Use ParseUser logininbackground function to enable this feature.
-User can log into account.
      -Gather new username and password
      -Use ParseUser signupinbackground function to enable this feature.
-User will stay logged in if they had already logged into their account.
